### model
## full-merged model
model_name_or_path: Qwen/Qwen2-VL-7B-Instruct
# model_name_or_path: /models/qwen2_vl-7b_visrl-stage1
trust_remote_code: true

### method
stage: dpo
do_train: true
finetuning_type: lora
lora_target: all
pref_beta: 0.1
pref_loss: sigmoid  # choices: [sigmoid (dpo), orpo, simpo]

### dataset
# stage1 use this
# dataset: demo_rl_data_stage1

# stage2 use this
dataset: demo_rl_data_stage1
template: qwen2_vl
cutoff_len: 2048
max_samples: 10000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/qwen2_vl-7b/lora/visrl-stage2
logging_steps: 10
save_steps: 200
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 3
gradient_accumulation_steps: 8
learning_rate: 5.0e-6
num_train_epochs: 5.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
seed: 88

### eval
val_size: 0.1
per_device_eval_batch_size: 3
eval_strategy: steps
eval_steps: 200
